
[functions.sendNotification]
enabled = true
verify_jwt = true
import_map = "./functions/sendNotification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sendNotification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sendNotification/*.html" ]

[functions.expo-delivery-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/expo-delivery-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/expo-delivery-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/expo-delivery-webhook/*.html" ]
